"""Phase E-10 — TAA Regime Tilt Visualization (rule-based overlay diagnostic).

E-10A: tilt diagnostic JSON (read-only)
E-10B: TAA PNG (6 panel: header / regime card / tilt policy / SAA→TAA bridge /
       before-after risk-return / limitation footer)

중요한 표현 제약 (사용자 명시):
- TAA 는 rule-based / heuristic overlay 임을 명시.
- "optimized TAA" / "regime-conditioned MVO" / "TAA optimization" 표현 사용 금지.
- 라벨: "Rule-based regime overlay", "Diagnostic before/after comparison",
        "Not regime-conditioned optimization".
"""

from __future__ import annotations

import json
import math
from copy import deepcopy
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SCHEMA_VERSION = "e10.1"
ZERO_WEIGHT_THRESHOLD = 0.005

REGIME_QUADRANT: dict[int, str] = {
    1: "Expansion / Acceleration",
    2: "Recovery / Improvement",
    3: "Slowdown / Contraction",
    4: "Late Cycle / Deceleration",
}

LIMITATION_TEXT = (
    "Current TAA is generated by a rule-based regime policy. "
    "Regime-conditioned expected returns/volatilities are not yet available. "
    "This is NOT regime-conditioned MVO and NOT optimized TAA."
)

METHOD_LABEL = "rule_based"


# ---------------------------------------------------------------------------
# Telemetry guards
# ---------------------------------------------------------------------------


def _require_taa_inputs(portfolio: dict[str, Any]) -> tuple[dict, dict, dict]:
    diag = portfolio.get("diagnostics") or {}
    saa = diag.get("saa_diagnostics") or {}
    taa = diag.get("taa_diagnostics") or {}
    cma = saa.get("cma") or {}
    if not saa.get("saa_weights"):
        raise ValueError(
            "E-10 TAA tilt requires direct SAA telemetry "
            "`diagnostics.saa_diagnostics.saa_weights` (E-6.2 T-6). "
            "Inferred SAA is forbidden."
        )
    feas = taa.get("taa_feasibility") or {}
    if not feas.get("target_weights_before_projection"):
        raise ValueError(
            "E-10 TAA tilt requires "
            "`diagnostics.taa_diagnostics.taa_feasibility.target_weights_before_projection`."
        )
    for need in ("expected_returns", "covariance_matrix"):
        if not cma.get(need):
            raise ValueError(
                f"E-10 TAA tilt requires `saa_diagnostics.cma.{need}` (E-6.2 T-1~T-4)."
            )
    return saa, taa, cma


# ---------------------------------------------------------------------------
# Numerical helpers
# ---------------------------------------------------------------------------


def _ordered_keys(cma: dict[str, Any], fallback: dict[str, float]) -> list[str]:
    keys = cma.get("asset_keys") or list(fallback.keys())
    return [str(k) for k in keys]


def _vec(d: dict[str, float], keys: list[str]) -> list[float]:
    return [float(d.get(k, 0.0)) for k in keys]


def _mat(d: dict[str, dict[str, float]], keys: list[str]) -> list[list[float]]:
    return [
        [float((d.get(ki) or {}).get(kj, 0.0)) for kj in keys]
        for ki in keys
    ]


def _matvec(mat: list[list[float]], v: list[float]) -> list[float]:
    n = len(v)
    out = [0.0] * n
    for i in range(n):
        s = 0.0
        row = mat[i]
        for j in range(n):
            s += row[j] * v[j]
        out[i] = s
    return out


def _portfolio_metrics(
    weights: list[float], er: list[float], cov: list[list[float]], rf: float
) -> tuple[float, float, float]:
    sigma_w = _matvec(cov, weights)
    var = sum(weights[i] * sigma_w[i] for i in range(len(weights)))
    var = max(var, 0.0)
    vol = math.sqrt(var)
    ret = sum(weights[i] * er[i] for i in range(len(weights)))
    sharpe = (ret - rf) / vol if vol > 1e-12 else float("nan")
    return ret, vol, sharpe


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


def build_taa_tilt(
    portfolio: dict[str, Any],
    *,
    taa_policy: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """portfolio + (옵션) taa_policy.yaml → TAA tilt diagnostic dict.

    raises ValueError if direct SAA / TAA feasibility / CMA telemetry missing.
    """
    saa_diag, taa_diag, cma = _require_taa_inputs(portfolio)
    feas = taa_diag.get("taa_feasibility") or {}
    regime = (portfolio.get("diagnostics") or {}).get("regime") or {}

    saa_w_dict = {str(k): float(v) for k, v in saa_diag["saa_weights"].items()}
    taa_w_dict = {
        str(k): float(v)
        for k, v in (feas.get("target_weights_before_projection") or {}).items()
    }
    keys = _ordered_keys(cma, saa_w_dict)
    er_v = _vec(cma["expected_returns"], keys)
    cov = _mat(cma["covariance_matrix"], keys)
    rf = float(saa_diag.get("rf") or 0.0)

    saa_v = _vec(saa_w_dict, keys)
    taa_v = _vec(taa_w_dict, keys)
    tilt_v = [taa_v[i] - saa_v[i] for i in range(len(keys))]

    # before / after metrics
    saa_ret, saa_vol, saa_sharpe = _portfolio_metrics(saa_v, er_v, cov, rf)
    taa_ret, taa_vol, taa_sharpe = _portfolio_metrics(taa_v, er_v, cov, rf)
    delta_sharpe = (taa_sharpe - saa_sharpe) if (
        math.isfinite(saa_sharpe) and math.isfinite(taa_sharpe)
    ) else None

    # asset_level_effect
    sigma_w_taa = _matvec(cov, taa_v)
    by_asset_effect: dict[str, dict[str, float]] = {}
    for i, ak in enumerate(keys):
        by_asset_effect[ak] = {
            "saa_weight": float(saa_v[i]),
            "tilt": float(tilt_v[i]),
            "taa_target_weight": float(taa_v[i]),
            "marginal_expected_return_effect": float(er_v[i] * tilt_v[i]),
            "marginal_risk_effect": float(sigma_w_taa[i] * tilt_v[i]),
            "contribution_to_delta_return": float(er_v[i] * tilt_v[i]),
        }

    # tilt_policy block (taa_policy.yaml::regime_tilts.<regime_id>)
    regime_id = int(regime.get("regime") or 0)
    policy_block: dict[str, Any] = {
        "policy_id": "taa_policy.yaml::regime_tilts",
        "policy_version": "phase-d frozen",
        "method": METHOD_LABEL,
        "description": (
            "Rule-based regime overlay. SAA + asset_tilts (per-regime fixed) "
            "→ TAA target; tilt_sum=0 정합. Not regime-conditioned MVO."
        ),
        "limitation_text": LIMITATION_TEXT,
    }
    regime_reason = ""
    asset_tilts_yaml: dict[str, float] = {}
    if taa_policy:
        regime_tilts = (taa_policy.get("regime_tilts") or {}).get(regime_id) or {}
        asset_tilts_yaml = regime_tilts.get("asset_tilts") or {}
        regime_reason = str(regime_tilts.get("reason") or "")
        policy_block["regime_label_yaml"] = str(regime_tilts.get("label") or "")
        policy_block["regime_reason"] = regime_reason

    # tilt_rules_applied — non-zero tilts (from yaml policy + applied tilts)
    tilt_rules: list[dict[str, Any]] = []
    for ak, w_raw in sorted(asset_tilts_yaml.items()):
        policy_tilt_pp = float(w_raw) * 100.0
        applied_tilt_pp = (taa_w_dict.get(ak, 0.0) - saa_w_dict.get(ak, 0.0)) * 100.0
        direction = (
            "overweight" if applied_tilt_pp > 1e-6
            else "underweight" if applied_tilt_pp < -1e-6
            else "neutral"
        )
        tilt_rules.append({
            "asset_key": ak,
            "saa_weight": float(saa_w_dict.get(ak, 0.0)),
            "tilt": float((applied_tilt_pp) / 100.0),
            "taa_target_weight": float(taa_w_dict.get(ak, 0.0)),
            "policy_tilt_pp": policy_tilt_pp,
            "applied_tilt_pp": applied_tilt_pp,
            "direction": direction,
            "rationale": (
                f"Regime {regime_id} → asset_tilts.{ak} = {policy_tilt_pp:+.2f}pp "
                f"(applied {applied_tilt_pp:+.2f}pp)"
            ),
            "source": METHOD_LABEL,
            "confidence": None,
        })

    # regime_context — 외부 E-8 산출물 path 만 reference (별도 첨부 안 함)
    payload: dict[str, Any] = {
        "meta": {
            "schema_version": SCHEMA_VERSION,
            "product_type": str(portfolio.get("portfolio_type") or ""),
            "portfolio_as_of_date": str(portfolio.get("as_of_date") or ""),
            "regime_signal_as_of_date": str(regime.get("as_of") or ""),
            "source_mode": str(portfolio.get("source_type") or "file"),
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
        "regime_context": {
            "current_regime": regime_id,
            "current_regime_label": str(regime.get("regime_label") or ""),
            "placement": float(regime.get("placement") or 0.0),
            "velocity": float(regime.get("velocity") or 0.0),
            "quadrant_label": REGIME_QUADRANT.get(regime_id, "Unknown"),
            "recent_transition_summary": (
                "history detail in E-8 sidecar regime_history_*.json"
            ),
            "regime_clock_reference": {
                "source_json": (
                    "out/db_review_relaxed_e62/regime_history/<as_of>/"
                    "regime_history_<pt>_<as_of>.json"
                ),
                "source_png": (
                    "out/db_review_relaxed_e62/regime_history/<as_of>/"
                    "regime_clock_<pt>_<as_of>.png"
                ),
            },
        },
        "tilt_policy": policy_block,
        "tilt_rules_applied": tilt_rules,
        "portfolio_before_after": {
            "saa": {
                "expected_return": float(saa_ret),
                "volatility": float(saa_vol),
                "sharpe": (float(saa_sharpe) if math.isfinite(saa_sharpe) else None),
                "weights": saa_w_dict,
            },
            "taa_target": {
                "expected_return": float(taa_ret),
                "volatility": float(taa_vol),
                "sharpe": (float(taa_sharpe) if math.isfinite(taa_sharpe) else None),
                "weights": taa_w_dict,
            },
            "delta": {
                "expected_return": float(taa_ret - saa_ret),
                "volatility": float(taa_vol - saa_vol),
                "sharpe": (float(delta_sharpe) if delta_sharpe is not None else None),
            },
            "label": "Diagnostic before/after comparison (rule-based overlay)",
        },
        "asset_level_effect": {
            "by_asset": by_asset_effect,
            "delta_return_check_sum": float(taa_ret - saa_ret),
        },
        "diagnostics": {
            "warnings": [],
            "missing_data": [
                {
                    "field": "regime_conditioned_assumptions",
                    "impact": "regime-aware MVO 비교 불가",
                    "recommended_next_step": (
                        "future phase — regime_mvo (currently future_study only)"
                    ),
                },
                {
                    "field": "tilt_rules_applied[].confidence",
                    "impact": "tilt 의 통계적 유의성 표시 불가",
                    "recommended_next_step": "future phase — confidence scaling",
                },
            ],
        },
    }
    return payload


def write_taa_tilt_json(payload: dict[str, Any], out_path: Path) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )
    return out_path


# ---------------------------------------------------------------------------
# PNG (E-10B)
# ---------------------------------------------------------------------------


def _select_korean_font() -> str | None:
    import matplotlib.font_manager as fm

    candidates = ("Malgun Gothic", "AppleGothic", "NanumGothic", "Gulim", "MS Gothic")
    available = {f.name for f in fm.fontManager.ttflist}
    for name in candidates:
        if name in available:
            return name
    return None


def render_taa_tilt(
    payload: dict[str, Any],
    out_path: Path,
    *,
    label: str | None = None,
) -> Path:
    """6-panel TAA PNG. read-only (deepcopy)."""
    payload = deepcopy(payload)

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib import gridspec as _gs
    import numpy as np

    font_name = _select_korean_font()
    if font_name:
        plt.rcParams["font.family"] = [font_name, "DejaVu Sans"]
    plt.rcParams["axes.unicode_minus"] = False

    meta = payload["meta"]
    rc = payload["regime_context"]
    pol = payload["tilt_policy"]
    rules = payload["tilt_rules_applied"]
    ba = payload["portfolio_before_after"]
    saa = ba["saa"]
    taa = ba["taa_target"]
    delta = ba["delta"]

    pt = (meta.get("product_type") or "").upper()

    fig = plt.figure(figsize=(14.0, 17.5))
    gs = _gs.GridSpec(
        nrows=6, ncols=2,
        height_ratios=[0.65, 1.4, 1.6, 3.0, 3.2, 0.55],
        width_ratios=[1.0, 1.0],
        hspace=0.55, wspace=0.20,
        left=0.07, right=0.97, top=0.97, bottom=0.04,
    )

    # 1. Header
    ax_h = fig.add_subplot(gs[0, :])
    ax_h.set_axis_off()
    ax_h.text(
        0.0, 0.85,
        f"TAA Regime Tilt — {pt} Portfolio  ·  Rule-Based Overlay Diagnostic",
        transform=ax_h.transAxes,
        fontsize=15, fontweight="bold", va="top",
    )
    ax_h.text(
        0.0, 0.45,
        f"portfolio as_of={meta.get('portfolio_as_of_date')}  ·  "
        f"regime signal as_of={meta.get('regime_signal_as_of_date')}  ·  "
        f"current regime={rc.get('current_regime')} "
        f"({rc.get('current_regime_label')})",
        transform=ax_h.transAxes, fontsize=10.5, color="#333", va="center",
    )
    ax_h.text(
        0.0, 0.10,
        f"method = {pol.get('method')}  ·  policy = {pol.get('policy_id')}  ·  "
        f"version = {pol.get('policy_version')}",
        transform=ax_h.transAxes, fontsize=9.5, color="#7a3a3a", va="bottom",
    )

    # 2. Regime context (left card + right reference)
    ax_rc = fig.add_subplot(gs[1, 0])
    ax_rc.set_axis_off()
    ax_rc.text(
        0.02, 0.92, "Regime Context",
        fontsize=11, fontweight="bold", transform=ax_rc.transAxes,
    )
    ax_rc.text(
        0.02, 0.74,
        f"R{rc.get('current_regime')}  {rc.get('quadrant_label')}",
        fontsize=11, transform=ax_rc.transAxes,
    )
    ax_rc.text(
        0.02, 0.55,
        f"Placement : {float(rc.get('placement') or 0):+.4f}",
        fontsize=10, transform=ax_rc.transAxes,
    )
    ax_rc.text(
        0.02, 0.40,
        f"Velocity  : {float(rc.get('velocity') or 0):+.4f}",
        fontsize=10, transform=ax_rc.transAxes,
    )
    ax_rc.text(
        0.02, 0.20,
        f"signal as_of: {meta.get('regime_signal_as_of_date')}",
        fontsize=10, color="#555", transform=ax_rc.transAxes,
    )
    ax_rc.text(
        0.02, 0.04,
        "Full trajectory: see E-8 regime_clock_*.png",
        fontsize=9, color="#888", style="italic", transform=ax_rc.transAxes,
    )

    # mini placement-velocity card (current point only — full clock 은 E-8 참조)
    ax_pv = fig.add_subplot(gs[1, 1])
    p = float(rc.get("placement") or 0.0)
    v = float(rc.get("velocity") or 0.0)
    pmax = max(abs(p), 0.05) * 1.6
    vmax = max(abs(v), 0.05) * 1.6
    ax_pv.fill_betweenx([0, vmax], 0, pmax, color="#3a8a3e", alpha=0.07)
    ax_pv.fill_betweenx([0, vmax], -pmax, 0, color="#3a6db0", alpha=0.07)
    ax_pv.fill_betweenx([-vmax, 0], -pmax, 0, color="#a83232", alpha=0.07)
    ax_pv.fill_betweenx([-vmax, 0], 0, pmax, color="#c97a2a", alpha=0.07)
    ax_pv.axhline(0, color="#444", linewidth=0.6)
    ax_pv.axvline(0, color="#444", linewidth=0.6)
    ax_pv.scatter([p], [v], s=240, marker="*", color="#222",
                  edgecolors="white", linewidths=1.4, zorder=5)
    ax_pv.set_xlim(-pmax, pmax)
    ax_pv.set_ylim(-vmax, vmax)
    ax_pv.set_xlabel("Placement", fontsize=9)
    ax_pv.set_ylabel("Velocity", fontsize=9)
    ax_pv.set_title(
        "current point only (full clock → E-8)",
        fontsize=9, color="#555", loc="center",
    )
    ax_pv.tick_params(labelsize=8)

    # 3. Tilt policy panel
    ax_pol = fig.add_subplot(gs[2, :])
    ax_pol.set_axis_off()
    ax_pol.text(
        0.0, 0.92, "Rule-Based Tilt Policy (current regime)",
        transform=ax_pol.transAxes, fontsize=12, fontweight="bold",
    )
    ow_list = [r for r in rules if r["direction"] == "overweight"]
    uw_list = [r for r in rules if r["direction"] == "underweight"]
    ow_text = (
        "  ".join([f"{r['asset_key']} {r['policy_tilt_pp']:+.2f}pp" for r in ow_list])
        or "(none)"
    )
    uw_text = (
        "  ".join([f"{r['asset_key']} {r['policy_tilt_pp']:+.2f}pp" for r in uw_list])
        or "(none)"
    )
    ax_pol.text(
        0.02, 0.66,
        f"Overweight  : {ow_text}",
        transform=ax_pol.transAxes, fontsize=10, color="#2a8a3e",
    )
    ax_pol.text(
        0.02, 0.42,
        f"Underweight : {uw_text}",
        transform=ax_pol.transAxes, fontsize=10, color="#a83232",
    )
    if pol.get("regime_reason"):
        ax_pol.text(
            0.02, 0.18,
            f"reason: {pol.get('regime_reason')}",
            transform=ax_pol.transAxes, fontsize=9, color="#555", style="italic",
        )
    ax_pol.text(
        0.02, 0.00,
        "Label: Rule-based overlay, NOT optimized TAA.",
        transform=ax_pol.transAxes, fontsize=9, color="#7a3a3a", fontweight="bold",
    )

    # 4. SAA → TAA asset bridge (diverging bar + table-like row)
    ax_br = fig.add_subplot(gs[3, :])
    asset_keys = [r["asset_key"] for r in rules]
    saa_pct = [r["saa_weight"] * 100 for r in rules]
    tilt_pp = [r["applied_tilt_pp"] for r in rules]
    taa_pct = [r["taa_target_weight"] * 100 for r in rules]
    if not asset_keys:
        ax_br.set_axis_off()
        ax_br.text(0.5, 0.5, "no policy tilts", ha="center", va="center")
    else:
        y = np.arange(len(asset_keys))
        colors = [
            "#2a8a3e" if t > 0 else "#a83232" if t < 0 else "#888"
            for t in tilt_pp
        ]
        bars = ax_br.barh(y, tilt_pp, color=colors)
        ax_br.set_yticks(y)
        ax_br.set_yticklabels(asset_keys)
        ax_br.invert_yaxis()
        ax_br.axvline(0, color="#333", linewidth=0.6)
        ax_br.set_xlabel("Applied tilt (%p)  =  TAA target − SAA")
        max_abs = max((abs(t) for t in tilt_pp), default=1.0) * 1.5
        ax_br.set_xlim(-max_abs, max_abs)
        ax_br.grid(axis="x", linestyle=":", alpha=0.4)
        # 우측 SAA / TAA 표 형식
        for i, (s, t, ta) in enumerate(zip(saa_pct, tilt_pp, taa_pct)):
            sign = "+" if t > 0 else ""
            ax_br.text(
                t + (max_abs * 0.02 if t >= 0 else -max_abs * 0.02),
                i,
                f"{sign}{t:.2f}pp",
                va="center", ha="left" if t >= 0 else "right",
                fontsize=9,
                color="#2a8a3e" if t > 0 else "#a83232" if t < 0 else "#444",
            )
        # right side: SAA / TAA 표
        for i, (ak, s, ta) in enumerate(zip(asset_keys, saa_pct, taa_pct)):
            ax_br.text(
                1.02, (len(asset_keys) - 1 - i) / max(len(asset_keys) - 1, 1),
                f"SAA {s:>6.2f}% → TAA {ta:>6.2f}%",
                transform=ax_br.transAxes, ha="left", va="center",
                fontsize=8.5, color="#444", family="monospace",
            )
    ax_br.set_title(
        "SAA → TAA Asset Bridge (rule-based regime tilt applied)",
        fontsize=12, fontweight="bold", loc="left",
    )

    # 5. Before / After risk-return
    ax_ba = fig.add_subplot(gs[4, :])
    saa_x = saa["volatility"] * 100
    saa_y = saa["expected_return"] * 100
    taa_x = taa["volatility"] * 100
    taa_y = taa["expected_return"] * 100
    # background gradient (μ-σ space)
    ax_ba.scatter(
        [saa_x], [saa_y], s=260, marker="o", color="#9aa3ad",
        edgecolors="white", linewidths=1.5, label=f"SAA  Sharpe={saa['sharpe']:.4f}",
        zorder=4,
    )
    ax_ba.scatter(
        [taa_x], [taa_y], s=300, marker="*", color="#3a6db0",
        edgecolors="white", linewidths=1.5,
        label=f"TAA target  Sharpe={taa['sharpe']:.4f}",
        zorder=5,
    )
    # arrow
    ax_ba.annotate(
        "", xy=(taa_x, taa_y), xytext=(saa_x, saa_y),
        arrowprops=dict(arrowstyle="->", color="#444", lw=1.4),
    )
    ax_ba.annotate(
        f"SAA\n{saa_y:.2f}% / {saa_x:.2f}%",
        xy=(saa_x, saa_y), xytext=(-90, -8), textcoords="offset points",
        fontsize=9, color="#444",
        bbox=dict(facecolor="white", edgecolor="#aaa", boxstyle="round,pad=0.3", alpha=0.9),
    )
    ax_ba.annotate(
        f"TAA target\n{taa_y:.2f}% / {taa_x:.2f}%",
        xy=(taa_x, taa_y), xytext=(20, 12), textcoords="offset points",
        fontsize=9, color="#3a6db0",
        bbox=dict(facecolor="white", edgecolor="#3a6db0", boxstyle="round,pad=0.3", alpha=0.9),
    )
    pad_x = max(abs(taa_x - saa_x), 0.5) * 3
    pad_y = max(abs(taa_y - saa_y), 0.5) * 3
    ax_ba.set_xlim(min(saa_x, taa_x) - pad_x, max(saa_x, taa_x) + pad_x)
    ax_ba.set_ylim(min(saa_y, taa_y) - pad_y, max(saa_y, taa_y) + pad_y)
    ax_ba.set_xlabel("Volatility (σ, %)", fontsize=10)
    ax_ba.set_ylabel("Expected return (μ, %)", fontsize=10)
    ax_ba.grid(linestyle=":", alpha=0.4)
    ax_ba.legend(loc="lower right", fontsize=9)
    ds_text = ""
    if delta.get("sharpe") is not None:
        sign = "+" if delta["sharpe"] >= 0 else ""
        ds_text = f"ΔSharpe = {sign}{delta['sharpe']:.4f}"
    ax_ba.text(
        0.02, 0.96,
        f"ΔE[R] = {delta['expected_return'] * 100:+.2f}pp   "
        f"Δσ = {delta['volatility'] * 100:+.2f}pp   {ds_text}",
        transform=ax_ba.transAxes, fontsize=11, fontweight="bold",
        color="#222", va="top",
        bbox=dict(facecolor="white", edgecolor="#888", boxstyle="round,pad=0.4", alpha=0.95),
    )
    ax_ba.set_title(
        "Diagnostic Before / After Comparison (rule-based overlay)",
        fontsize=12, fontweight="bold", loc="left",
    )

    # 6. Footer / limitation
    ax_f = fig.add_subplot(gs[5, :])
    ax_f.set_axis_off()
    ax_f.text(
        0.5, 0.5, LIMITATION_TEXT,
        transform=ax_f.transAxes, ha="center", va="center",
        fontsize=10, color="#7a3a3a", fontweight="bold",
        bbox=dict(facecolor="#fff5f5", edgecolor="#a83232", boxstyle="round,pad=0.5", alpha=0.9),
    )

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=140)
    plt.close(fig)
    return out_path


# ---------------------------------------------------------------------------
# Summary md
# ---------------------------------------------------------------------------


def render_taa_tilt_summary_md(
    *,
    as_of_run: str,
    etf_payload: dict[str, Any],
    fund_payload: dict[str, Any],
    etf_png_rel: str,
    fund_png_rel: str,
    out_path: Path,
) -> Path:
    lines: list[str] = []
    lines.append(f"# TAA Regime Tilt Summary ({as_of_run})")
    lines.append("")
    lines.append(f"> schema_version: {SCHEMA_VERSION}")
    lines.append(f"> {LIMITATION_TEXT}")
    lines.append("")
    for label, payload, png_rel in (
        ("ETF", etf_payload, etf_png_rel),
        ("Fund", fund_payload, fund_png_rel),
    ):
        meta = payload["meta"]
        rc = payload["regime_context"]
        ba = payload["portfolio_before_after"]
        delta = ba["delta"]
        rules = payload["tilt_rules_applied"]
        lines.append(f"## {label}")
        lines.append("")
        lines.append(
            f"- regime: **R{rc['current_regime']} {rc['quadrant_label']}**, "
            f"P={rc['placement']:+.4f}, V={rc['velocity']:+.4f}"
        )
        lines.append(
            f"- portfolio as_of={meta['portfolio_as_of_date']}, "
            f"regime signal as_of={meta['regime_signal_as_of_date']}"
        )
        lines.append(
            f"- SAA: E[R]={ba['saa']['expected_return'] * 100:.2f}%, "
            f"σ={ba['saa']['volatility'] * 100:.2f}%, Sharpe={ba['saa']['sharpe']:.4f}"
        )
        lines.append(
            f"- TAA: E[R]={ba['taa_target']['expected_return'] * 100:.2f}%, "
            f"σ={ba['taa_target']['volatility'] * 100:.2f}%, "
            f"Sharpe={ba['taa_target']['sharpe']:.4f}"
        )
        lines.append(
            f"- Δ: E[R]={delta['expected_return'] * 100:+.2f}pp, "
            f"σ={delta['volatility'] * 100:+.2f}pp, "
            f"Sharpe={delta['sharpe']:+.4f}"
        )
        lines.append("- Applied tilts:")
        for r in rules:
            if abs(r["applied_tilt_pp"]) < 1e-6:
                continue
            sign = "+" if r["applied_tilt_pp"] > 0 else ""
            lines.append(
                f"  - {r['asset_key']}: SAA {r['saa_weight'] * 100:.2f}% "
                f"→ TAA {r['taa_target_weight'] * 100:.2f}% "
                f"(tilt {sign}{r['applied_tilt_pp']:.2f}pp, {r['direction']})"
            )
        lines.append("")
        lines.append(f"![{label} TAA Tilt]({png_rel})")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"**Limitation**: {LIMITATION_TEXT}")
    lines.append("")
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


__all__ = [
    "SCHEMA_VERSION",
    "LIMITATION_TEXT",
    "METHOD_LABEL",
    "build_taa_tilt",
    "write_taa_tilt_json",
    "render_taa_tilt",
    "render_taa_tilt_summary_md",
]
